net start OracleDBConsoleorcl
net start OracleVssWriterORCL
net start OracleJobSchedulerORCL
net start OracleMTSRecoveryService
net start OracleOraDb11g_home1ClrAgent
net start OracleOraDb11g_home1TNSListener
net start OracleServiceORCL
