net stop OracleDBConsoleorcl
net stop OracleVssWriterORCL
net stop OracleJobSchedulerORCL
net stop OracleMTSRecoveryService
net stop OracleOraDb11g_home1ClrAgent
net stop OracleOraDb11g_home1TNSListener
net stop OracleServiceORCL
